# Generated by Django 3.2.3 on 2023-04-09 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(limit_value=200)], verbose_name='Название ингридиента')),
                ('measurement_unit', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(limit_value=200)], verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['-id'],
            },
        ),
    ]
