# Generated by Django 3.2.3 on 2023-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230423_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                default=None, null=True, upload_to='recipes/images/'
            ),
        ),
    ]
