# Generated by Django 3.2.3 on 2023-04-12 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20230411_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 200 characters or fewer.', max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)], verbose_name='Название избранного блюда')),
                ('cooking_time', models.IntegerField(help_text='Required. 10 characters or fewer.', max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=10), recipes.validators.validate_cooking_time, django.core.validators.validate_integer], verbose_name='Время приготовления')),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик на рецепт')),
                ('recipe_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='recipes.recipe', verbose_name='В избранном')),
            ],
        ),
    ]
