# Generated by Django 3.2.3 on 2023-04-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230409_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
