# Generated by Django 3.2.3 on 2023-04-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230423_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Тег/Рецепт',
                'verbose_name_plural': 'Теги в рецептах',
            },
        ),
    ]
