# Generated by Django 3.2.3 on 2023-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
