# Generated by Django 3.2.3 on 2023-04-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230409_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
