# Generated by Django 3.2.3 on 2023-04-10 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. 254 characters or fewer.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MaxLengthValidator(limit_value=254)]),
        ),
    ]
